### ISSUE TITLE
Lag if drag a seekbar

### ISSUE THREAD

**Issue by webserveis** [HugoGresse/AndroidVuMeter#12]
Lag in equalizer view animation when drag a seekbar in the layout.

My seekbar is sincronized change value of volume stream audio

**Comment by HugoGresse** [comment]
Hi, 

Can you make a short video/gif to show the issue?

**Comment by francislanthier** [comment]
I'm also getting this issue. Only on a Pixel XL. I've used a Samsung note 3 and I cannot reproduce the issue on this phone. Weird !

**Comment by HugoGresse** [comment]
it could be hard for me to see what's going on. Are you able to make a short video about the issue?
