### ISSUE TITLE
Failed to resolve when syncing gradle files

### ISSUE THREAD

**Issue by NomadicDeveloper22** [HugoGresse/AndroidVuMeter#16]
I keep getting "Failed to resolve: io.gresse.hugo.vumeterlibrary:vumeterlibrary:1.0.16" when trying to implement the library in gradle

Only line of code I have added related to VuMeter is `implementation 'net.alhazmy13.catcho:library:1.1.0'` in my build.gradle file

I also have `jcenter()` as one of my repositories

**Comment by FitApps7** [comment]
use this, I have solved by this
implementation 'io.gresse.hugo.vumeterlibrary:vumeterlibrary:1.0.11'

**Comment by HugoGresse** [comment]
Wow so much delay on my side here. The latest version is `1.0.17` and is available on jCenter. Sorry for the issue.
