### ISSUE TITLE
How to turn off auto start?

### ISSUE THREAD

**Issue by mladenrakonjac** [HugoGresse/AndroidVuMeter#2]

**Comment by HugoGresse** [comment]
There is no option currently, what you can do currently is to call `stop()` after findViewById. I will add an option to set it view xml.

**Comment by mladenrakonjac** [comment]
If I use stop() it doesn't work as I want to work. So, I will be very grateful if you add it. Thank you for answer :)

**Comment by HugoGresse** [comment]
Will do it in 3hrs ,)

**Comment by HugoGresse** [comment]
released in v1.0.10
