### ISSUE TITLE
How can i change the with between the bars?

### ISSUE THREAD

**Issue by mistapetroz** [HugoGresse/AndroidVuMeter#8]
By the way this repo is sooo cool but i cant seen to wrap my head around changing the bars to be more close together coz i see you made it such that they are separated with the same width as their own. 

UPDATE:
found it in the xml

**Comment by mistapetroz** [comment]
Dont even bother i found it ... in the xml

**Comment by HugoGresse** [comment]
glad to hear, thanks for closing it ;)
