### ISSUE TITLE
Error parsing XML: unbound prefix when put io.gresse.hugo.vumeterlibrary.VuMeterView in layout

### ISSUE THREAD

**Issue by guangwei** [HugoGresse/AndroidVuMeter#9]
very nice job!

I just want to report this issue to remind an update in the user manual, and I'v find the solution:

add the name space vumeter  by add this line:

xmlns:vumeter="http://schemas.android.com/apk/res-auto"

**Comment by HugoGresse** [comment]
glad you find the solution, I'll update the readme to prevent this ;)
